# Config file for PhantomX Reactor
port: /dev/ttyUSB_REACTOR
rate: 100
joints: {
  arm_shoulder_yaw_joint: {id: 1, max_speed: 50.0},
  arm_shoulder_pitch_joint: {id: 2, max_speed: 50.0},
  arm_shoulder_pitch_mimic_joint: {id: 3, max_speed: 50.0},
  arm_elbow_pitch_joint: {id: 5, max_speed: 50.0},
  arm_elbow_pitch_mimic_joint: {id: 4, max_speed: 50.0},
  arm_wrist_pitch_joint: {id: 6, max_speed: 50.0, invert: true},
  arm_wrist_roll_joint: {id: 7, max_speed: 50.0},
  arm_gripper_revolute_joint: {id: 8, max_speed: 100.0, range: 180, min_angle: −90.0, max_angle: 0},
}

controllers: {
  arm_controller: {
    type: 'follow_controller',
    rate: 100,
    joints: [
            'arm_shoulder_yaw_joint',
            'arm_shoulder_pitch_joint',
            'arm_shoulder_pitch_mimic_joint',
            'arm_elbow_pitch_joint',
            'arm_elbow_pitch_mimic_joint',
            'arm_wrist_pitch_joint',
            'arm_wrist_roll_joint'
            ]
   action_name: 'arm_controller/follow_joint_trajectory'
  }
  grip_controller: {
    type: 'follow_controller',
    rate: 100,
    joints: [
            'arm_gripper_revolute_joint'
            ]
    action_name: 'grip_controller/follow_joint_trajectory'
  }
}

