#
# phantomx_reactor_controllers.yaml
#
# Author: Daniel Lozano Moreno
# File created for the final degree project in robotics engineering at
# the University of Alicante (UA), promotion of 2021-2022. Proyect Name:
# Control y simulacion en ROS de un PhatomX Reactor Arm en cooperacion
# con un TurtleBot2 (Control and simulation in ROS of a PhatomX Reactor 
# Arm in cooperation with a TurtleBot2).
#
# Group controllers for the arm and hand of PhantomX Reactor without Turtlebot

# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Arm Controllers ---------------------------------------
arm_controller:
   type: "position_controllers/JointTrajectoryController"
   joints:
     - shoulder_yaw_joint
     - shoulder_pitch_joint
     - elbow_pitch_joint
     - wrist_pitch_joint
     - wrist_roll_joint

# Gripper controller ---------------------------------------
grip_controller:
   type: "position_controllers/JointTrajectoryController"
   joints: 
     - gripper_right_joint

# Gazebor PID controllers
gazebo_ros_control:
  pid_gains:
    shoulder_yaw_joint:
      p: 700.0
      i: 0.1
      d: 0.1
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    shoulder_pitch_joint:
      p: 600.0
      i: 1.0
      d: 0.1
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    elbow_pitch_joint:
      p: 100.0
      i: 5.0
      d: 0.5
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    wrist_pitch_joint:
      p: 100.0
      i: 0.1
      d: 0.1
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    wrist_roll_joint:
      p: 20.0
      i: 0.01
      d: 0.01
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    gripper_right_joint:
      p: 100.0
      i: 1.0
      d: 0.1
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
      
    gripper_left_joint:
      p: 100.0
      i: 1.0
      d: 0.1
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
